# templates/migration-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-migration
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-db-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      {{- if not .Values.community.config.database.external }}
      initContainers:
      - name: wait-for-postgres
        image: postgres:15-alpine
        command:
          - /bin/sh
          - -c
          - |
            echo "Waiting for PostgreSQL..."
            until pg_isready -h {{ .Release.Name }}-postgresql -p 5432 -U {{ .Values.community.config.postgresql.username }}; do
              sleep 2
            done
            echo "PostgreSQL is ready"
      {{- end }}
      containers:
      - name: db-migration
        image: "{{ .Values.community.image.repository }}:{{ .Values.community.image.tag }}"
        command: 
          - /bin/sh
          - -c
          - |
            echo "Running database migrations..."
            pnpx prisma migrate deploy
        env:
          {{- with .Values.community.migration.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
